name: filesyncerr
#
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
    
jobs:
  syncjob1:
    runs-on: ubuntu-latest
    name: SyncerrJOB1

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          wget -qO- https://api.github.com/repos/donwa/gclone/releases/latest \
          | grep browser_download_url | grep Linux_x86_64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- | gzip -d -c > rclone
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: Config
        run: |
          mkdir -p ~/.config/rclone
          mkdir -p sa
          cd sa
          curl -L "${{ secrets.CLONE_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          rm accounts.zip
          cd ..
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.CLONE_CONFIG_SYNC }}
          EOF
      - name: syncRun
        run: |
          echo "::add-mask::gclone sa file: /home/runner/.config/rclone/sa/"
          echo "::add-mask::.json"
          rclone copy gdrive:"/Transfer/Pahe Final/Pahe Part 1" onedrive1:"/Pahe Part 1" --stats=30s --stats-one-line -P --checkers=320 --transfers=320 --drive-pacer-min-sleep=1ms --drive-pacer-burst=4000 --fast-list
